CREATE TABLE "public"."favorites" (
  "id"         bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp(6) without time zone NOT NULL,
  "file_id"    bigint                         NOT NULL,
  "user_id"    bigint                         NOT NULL,
  CONSTRAINT "favorites_pkey" PRIMARY KEY (id),
  CONSTRAINT "uq_user_file_favorite" UNIQUE (user_id, file_id)
);

CREATE TABLE "public"."file_download_events" (
  "id"         bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp(6) without time zone NOT NULL,
  "file_id"    bigint                         NOT NULL,
  "user_id"    bigint,
  CONSTRAINT "file_download_events_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."file_hashtags" (
  "file_id"    bigint NOT NULL,
  "hashtag_id" bigint NOT NULL,
  CONSTRAINT "file_hashtags_pkey" PRIMARY KEY (file_id, hashtag_id)
);

CREATE TABLE "public"."file_ratings" (
  "id"         bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp(6) without time zone NOT NULL,
  "score"      integer                        NOT NULL,
  "updated_at" timestamp(6) without time zone NOT NULL,
  "file_id"    bigint                         NOT NULL,
  "user_id"    bigint                         NOT NULL,
  CONSTRAINT "file_ratings_pkey" PRIMARY KEY (id),
  CONSTRAINT "uq_user_file_rating" UNIQUE (user_id, file_id)
);

CREATE TABLE "public"."hashtags" (
  "id"   bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying(100) NOT NULL,
  CONSTRAINT "hashtags_pkey" PRIMARY KEY (id),
  CONSTRAINT "ukoed8qhhrhflqj7olh3oeii6ym" UNIQUE (name)
);

CREATE TABLE "public"."notifications" (
  "id"         bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "body"       text                           NOT NULL,
  "created_at" timestamp(6) without time zone NOT NULL,
  "is_read"    boolean                        NOT NULL,
  "target_id"  bigint,
  "title"      character varying(255)         NOT NULL,
  "type"       character varying(50)          NOT NULL,
  "user_id"    bigint,
  CONSTRAINT "notifications_pkey" PRIMARY KEY (id),
  CONSTRAINT "notifications_type_check" CHECK (((type)::text = ANY ((ARRAY['PROJECT'::character varying, 'FILE'::character varying, 'GENERAL'::character varying])::text[])))
);

CREATE TABLE "public"."suggestions" (
  "id"             bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attachment_url" character varying(1000),
  "created_at"     timestamp(6) without time zone NOT NULL,
  "message"        text                           NOT NULL,
  "status"         character varying(50)          NOT NULL,
  "user_id"        bigint                         NOT NULL,
  CONSTRAINT "suggestions_pkey" PRIMARY KEY (id),
  CONSTRAINT "suggestions_status_check" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'REVIEWED'::character varying, 'RESOLVED'::character varying])::text[])))
);

CREATE TABLE "public"."user_file_downloads" (
  "id"            bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "downloaded_at" timestamp(6) without time zone NOT NULL,
  "file_id"       bigint                         NOT NULL,
  "user_id"       bigint                         NOT NULL,
  CONSTRAINT "uq_user_file_download" UNIQUE (user_id, file_id),
  CONSTRAINT "user_file_downloads_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."workshop_attachments" (
  "id"         bigint                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "file_name"  character varying(255)  NOT NULL,
  "file_url"   character varying(1000) NOT NULL,
  "project_id" bigint                  NOT NULL,
  CONSTRAINT "workshop_attachments_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."workshop_projects" (
  "id"                     bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"             timestamp(6) without time zone NOT NULL,
  "description"            text                           NOT NULL,
  "form_link"              character varying(1000),
  "project_type"           character varying(50)          NOT NULL,
  "registration_closes_at" timestamp(6) without time zone NOT NULL,
  "registration_opens_at"  timestamp(6) without time zone NOT NULL,
  "status"                 character varying(50)          NOT NULL,
  "title"                  character varying(255)         NOT NULL,
  "author_id"              bigint                         NOT NULL,
  CONSTRAINT "workshop_projects_pkey" PRIMARY KEY (id),
  CONSTRAINT "workshop_projects_project_type_check"
    CHECK (((project_type)::text = ANY ((ARRAY['MOTIVATION'::character varying, 'FIRST_COME_FIRST_SERVED'::character varying])::text[]))),
  CONSTRAINT "workshop_projects_status_check"
    CHECK (((status)::text = ANY ((ARRAY['UPCOMING'::character varying, 'OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE "public"."study_files"
  ADD COLUMN "avg_rating" double precision NOT NULL;

ALTER TABLE "public"."study_files"
  ADD COLUMN "total_ratings" integer NOT NULL;

ALTER TABLE "public"."users"
  ADD COLUMN "full_name" character varying(255);

ALTER TABLE "public"."users"
  ADD COLUMN "last_login_at" timestamp(6) WITHOUT time zone;

ALTER TABLE "public"."users"
  ADD COLUMN "phone_number" character varying(50);

ALTER TABLE "public"."favorites"
  ADD CONSTRAINT "fk5f7187rooeqe1toibv6e5kkpr" FOREIGN KEY (file_id) REFERENCES public.study_files(id);

ALTER TABLE "public"."favorites"
  ADD CONSTRAINT "fkk7du8b8ewipawnnpg76d55fus" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."file_download_events"
  ADD CONSTRAINT "fk92v99el382jahqe1uqnomui4o" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."file_download_events"
  ADD CONSTRAINT "fkshihguihnp0sicmj05ep0907a" FOREIGN KEY (file_id) REFERENCES public.study_files(id);

ALTER TABLE "public"."file_hashtags"
  ADD CONSTRAINT "fkfb308pr4wp8q460atcbijfoda" FOREIGN KEY (file_id) REFERENCES public.study_files(id);

ALTER TABLE "public"."file_ratings"
  ADD CONSTRAINT "fk8w6caqf6e6knnly6qn9bswn1i" FOREIGN KEY (file_id) REFERENCES public.study_files(id);

ALTER TABLE "public"."file_ratings"
  ADD CONSTRAINT "fk90a9w9up9xxarh96hhs5syqud" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."file_hashtags"
  ADD CONSTRAINT "fk11q6cxfjc53wig3ko9s0akn4b" FOREIGN KEY (hashtag_id) REFERENCES public.hashtags(id);

ALTER TABLE "public"."notifications"
  ADD CONSTRAINT "fk9y21adhxn0ayjhfocscqox7bh" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."suggestions"
  ADD CONSTRAINT "fk7yns86oadd04hrdcstg7mhirm" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."user_file_downloads"
  ADD CONSTRAINT "fk27ixmw8r0b1l2t6dfe6condjh" FOREIGN KEY (file_id) REFERENCES public.study_files(id);

ALTER TABLE "public"."user_file_downloads"
  ADD CONSTRAINT "fkhh1b40hlyfvh5i0idcxugmyl7" FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE "public"."workshop_projects"
  ADD CONSTRAINT "fkmrx8499i8amb07p5e4tcj2uty" FOREIGN KEY (author_id) REFERENCES public.users(id);

ALTER TABLE "public"."workshop_attachments"
  ADD CONSTRAINT "fk2g50an2qhlco3nm8pmvwfev4a" FOREIGN KEY (project_id) REFERENCES public.workshop_projects(id);

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."favorites" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."favorites" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."favorites" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_download_events" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."file_download_events" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_download_events" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_hashtags" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."file_hashtags" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_hashtags" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_ratings" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."file_ratings" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."file_ratings" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."hashtags" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."hashtags" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."hashtags" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notifications" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."notifications" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."suggestions" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."suggestions" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."suggestions" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_file_downloads" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_file_downloads" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."user_file_downloads" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."workshop_attachments" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."workshop_attachments" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."workshop_attachments" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."workshop_projects" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."workshop_projects" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."workshop_projects" TO "service_role";
