ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."categories" (
  "id"          bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "description" text,
  "name"        character varying(255)         NOT NULL,
  "created_at"  timestamp(6) without time zone NOT NULL,
  CONSTRAINT "categories_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."reasonings" (
  "id"          bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "content"     text,
  "created_at"  timestamp(6) without time zone NOT NULL,
  "title"       character varying(255)         NOT NULL,
  "category_id" bigint                         NOT NULL,
  CONSTRAINT "reasonings_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."study_files" (
  "id"              bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "file_name"       character varying(255)         NOT NULL,
  "file_size_bytes" bigint,
  "file_type"       character varying(255),
  "public_url"      character varying(1000)        NOT NULL,
  "storage_key"     character varying(500)         NOT NULL,
  "uploaded_at"     timestamp(6) without time zone NOT NULL,
  "reasoning_id"    bigint                         NOT NULL,
  CONSTRAINT "study_files_pkey" PRIMARY KEY (id)
);

CREATE TABLE "public"."users" (
  "id"            bigint                         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"    timestamp(6) without time zone NOT NULL,
  "email"         character varying(255),
  "password_hash" character varying(255),
  "role"          character varying(50)          NOT NULL,
  "otp_code"      character varying(6),
  "otp_expiry"    timestamp(6) without time zone,
  CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE (email),
  CONSTRAINT "users_pkey" PRIMARY KEY (id),
  CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['ROLE_STUDENT'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);

ALTER TABLE "public"."reasonings"
  ADD CONSTRAINT "fkthg3vwk8ywwipnphxgdeayfpa" FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE "public"."study_files"
  ADD CONSTRAINT "fka27a2hodb8mveko8hrx2b07fn" FOREIGN KEY (reasoning_id) REFERENCES public.reasonings(id);

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."categories" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."categories" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."categories" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reasonings" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reasonings" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reasonings" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."study_files" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."study_files" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."study_files" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."users" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."users" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

